# Default values for kiem-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


kiem:
  image:
    repository: accuknox/kiem
    tag: "latest"

accuknoxJob:
  image:
    repository: accuknox/accuknox-job
    tag: "latest"

# To use existing secret, updated {imagePullSecrets.name} with your secret name.
imagePullSecrets:
  name: ""
  registry: ""
  username: ""
  password: ""


replicaCount: 1

accuknox:
  authToken: "NO-TOKEN-SET"
  URL: "cspm.demo.accuknox.com"
  tenantID: ""
  cronTab: "30 9 * * *"
  clusterName: ""
  label: ""
  certBundlePath: ""  # Set this for cert local path if needed .
  certBundleURL: ""  # Set this for cert URL if needed (if certBundlePath is set as well certBundlePath will take precedent)
  useInsecureConnection: false  # Set to true if insecure connection is needed

