apiVersion: batch/v1
kind: Job
metadata:
  name: kiem-job
  namespace: {{ .Release.Namespace }}
spec:
  # keep the job for 2 hours after successful completion
  ttlSecondsAfterFinished: 7200
  template:
    metadata:
      labels:
        app: kiem-job
    spec:
    {{- if .Values.imagePullSecrets.name }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
    {{- end }}    
      initContainers:
        - name: kiem-init
          image: accuknox/kiem:latest
          args: ["./kiem", "run", "--mode", "k8s", "--output", "/data/report.json"]
          env:
            - name: CLUSTER_NAME
              value: {{ .Values.accuknox.clusterName }}
          volumeMounts:
            - name: datapath
              mountPath: /data
      containers:
        - image: accuknox/accuknox-job:latest

          command: ["/bin/sh", "-c"]
          args: ['./curl_command.sh']

          name: accuknox-kiem-job
          resources: {}
          env:
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  key: AUTH_TOKEN
                  {{- if (.Values.accuknox.secretName | empty) }}
                  name: kiem-job-auth-token
                  {{- else }}
                  name: {{ .Values.accuknox.secretName }}
                  {{- end }}
            - name: URL
              value: {{ .Values.accuknox.URL }}
            - name: TENANT_ID
              value: {{ .Values.accuknox.tenantID | quote }}
            - name: CLUSTER_NAME
              value: {{ .Values.accuknox.clusterName }}
            - name: LABEL_NAME
              value: {{ .Values.accuknox.label | quote}}
            - name: CERT_BUNDLE_PATH
              value: {{ .Values.accuknox.certBundlePath | quote }}   
            - name: CERT_BUNDLE_URL
              value: {{ .Values.accuknox.certBundleURL }}
            - name: USE_INSECURE_CONNECTION
              value: {{ .Values.accuknox.useInsecureConnection | quote }}
            - name: DATA_TYPE
              value: "KIEM"
          volumeMounts:
            - mountPath: /data
              name: datapath      
      volumes:
        - name: datapath
          emptyDir: {}
      restartPolicy: OnFailure
      serviceAccount: kiem-service-account
