apiVersion: batch/v1
kind: Job
metadata:
  name: kiem-job
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      labels:
        app: kiem-job
    spec:
      initContainers:
        - name: kiem-init
          image: accuknox/kiem:latest
          args: ["./kiem", "run", "--mode", "k8s", "--output", "/data/report.json"]
          env:
            - name: CLUSTER_NAME
              value: {{ .Values.accuknox.clusterName }}
          volumeMounts:
            - name: datapath
              mountPath: /data
      containers:
        - image: accuknox/accuknox-job:latest
          command: ["/bin/sh", "-c"]
          args: ['./curl_command.sh']
          name: accuknox-kiem-job
          resources: {}
          env:
            - name: URL
              value: {{ .Values.accuknox.URL }}
            - name: TENANT_ID
              value: {{ .Values.accuknox.tenantID | quote }}
            - name: AUTH_TOKEN
              value: {{ .Values.accuknox.authToken }}
            - name: CLUSTER_NAME
              value: {{ .Values.accuknox.clusterName }}
            - name: LABEL_NAME
              value: {{ .Values.accuknox.label | quote}}
            - name: CERT_BUNDLE_PATH
              value: {{ .Values.accuknox.certBundlePath | quote }}   
            - name: CERT_BUNDLE_URL
              value: {{ .Values.accuknox.certBundleURL }}
            - name: USE_INSECURE_CONNECTION
              value: {{ .Values.accuknox.useInsecureConnection | quote }}
            - name: DATA_TYPE
              value: "KIEM"
          volumeMounts:
            - mountPath: /data
              name: datapath      
      volumes:
        - name: datapath
          emptyDir: {}
      restartPolicy: OnFailure
      serviceAccount: kiem-service-account