apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kiem-cluster-role
rules:
  - apiGroups:
        - ""
        - extensions
        - apps
        - rbac.authorization.k8s.io
        - roles.rbac.authorization.k8s.io
        - authorization.k8s.io
        - certificates.k8s.io
        - apiextensions.k8s.io
    resources: ["*"]
    verbs:  ["*"]
