# Global values that apply to the entire chart or sub-charts
global:
  accuknox:
    url: ""
    tenantId: ""
    authToken: "" 
    cronTab: ""
    clusterName: ""
    label: ""
    secretName: ""

# Values specific to accuknox-jobs sub-chart
accuknoxJobs:
  cis:
    enabled: false  
    toolConfig:
      platform: ""  
      nodeType: "worker"
      targets: ""
      benchmark: ""
      check: ""
      skip: ""
  riskassessment:
    enabled: false  
  kiem:
    enabled: false 