# Global parameters applicable to all jobs
global:
  url: "cspm.demo.accuknox.com"
  tenantId: ""
  authToken: "NO-TOKEN-SET"
  cronTab: "30 9 * * *"  
  clusterName: ""
  clusterId: ""
  label: ""   

# Job-specific configurations
accuknox:
  cis:
    enabled: false  # Default: CIS job is disabled
    promptForPlatform: false  # By default, platform selection is not prompted
    toolConfig:
      platform: ""  # Default platform value (empty unless set)      
  riskassessment:
    enabled: false
  # k8tls:
  #   enabled: false
  kiem:
    enabled: false   
