apiVersion: batch/v1
kind: CronJob
metadata:
  name: accuknox-kiem-job
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ .Values.accuknox.cronTab }}"  
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1

  jobTemplate:
    metadata:
      labels:
        app: accuknox-kiem-job
    spec:
      template:
        spec:
          initContainers:
            - name: kiem-init
              image: accuknox/kiem:latest
              args: ["./kiem", "run", "--mode", "k8s", "--output", "/data/report.json"]
              env:
                - name: CLUSTER_NAME
                  value: {{ .Values.accuknox.clusterName }}
              volumeMounts:
                - name: datapath
                  mountPath: /data
          containers:
            - image: accuknox/accuknox-job:latest
              command: ["/bin/sh", "-c"]
              args: ["curl --location --request POST 'https://cspm.dev.accuknox.com/api/v1/artifact/?tenant_id=$TENANT_ID&data_type=KIEM&save_to_s3=false' --header 'Tenant-Id: $TENANT_ID' --header "Authorization: Bearer $AUTH_TOKEN" --form 'file=@"/data/report.json"'"]
              name: accuknox-kiem-cronjob
              resources: {}
              env:
                - name: TENANT_ID
                  value: {{ .Values.accuknox.tenantId }}
                - name: AUTH_TOKEN
                  value: {{ .Values.accuknox.authToken }}
                - name: CLUSTER_NAME
                  value: {{ .Values.accuknox.clusterName }}
                - name: LABEL_NAME
                  value: {{ .Values.accuknox.z }}
              volumeMounts:
                - mountPath: /data
                  name: datapath      
          volumes:
            - name: datapath
              emptyDir: {}
          restartPolicy: OnFailure
          serviceAccount: kiem-service-account


