apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubescape-clusterrole
rules:
  - apiGroups:
    - ""
    - extensions
    - apps
    - batch
    - rbac.authorization.k8s.io
    - roles.rbac.authorization.k8s.io
    - authorization.k8s.io
    - certificates.k8s.io
    - apiextensions.k8s.io
    - admissionregistration.k8s.io
    - networking.k8s.io
    resources: ["*"]
    verbs:  ["*"]
