apiVersion: v1
kind: ConfigMap
metadata:
  name: accuknox-kubescape-cronjob-script-configmap
  namespace: {{ .Release.Namespace }}
data:
  augment-and-push-results.sh: |
    #! /bin/env bash

    cat <<< $(jq ". +=
      {
        "accuknox_metadata": {
          "cluster_name":"'$ENV.CLUSTER_NAME'",
          "label_name":"'$ENV.LABEL_NAME'"
        }
      }" /data/report.json) > /data/report.json

    curl --location --request POST \
    --header "Authorization: Bearer ${AUTH_TOKEN}" \
    --header "Tenant-Id: ${TENANT_ID}" \
    --form "file=@\"/data/report.json\"" \
    "https://${URL}/api/v1/artifact/?tenant_id=${TENANT_ID}&data_type=kubescape&save_to_s3=false"
