apiVersion: batch/v1
kind: Job
metadata:
  name: k8tls-job
  namespace: {{ .Release.Namespace }}
spec:
  # keep the job for 2 hours after successful completion
  ttlSecondsAfterFinished: 7200
  template:
    metadata:
      name: k8tls-job
    spec:
    {{- if .Values.imagePullSecrets.name }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
    {{- end }}    
      serviceAccountName: k8tls-serviceact
      containers:
      - image: "{{ .Values.accuknoxJob.image.repository }}:{{ .Values.accuknoxJob.image.tag }}"
        command: ["/bin/sh", "-c"]
        args: ['./curl_command.sh']
        name: k8tls-job
        resources: {}
        env:
          - name: AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                key: AUTH_TOKEN
                {{- if (.Values.accuknox.secretName | empty) }}
                name: k8tls-job-auth-token
                {{- else }}
                name: {{ .Values.accuknox.secretName }}
                {{- end }}
          - name: URL
            value: {{ .Values.accuknox.URL }}
          - name: TENANT_ID
            value: {{ .Values.accuknox.tenantID | quote }}
          - name: CLUSTER_NAME
            value: {{ if ne .Values.accuknox.clusterName "" }}{{ .Values.accuknox.clusterName }}{{ else }}{{ "default" }}{{ end }}
          - name: LABEL_NAME
            value: {{ if ne .Values.accuknox.label "" }}{{ .Values.accuknox.label }}{{ else }}{{ "default" }}{{ end }}
          - name: CERT_BUNDLE_PATH
            value: {{ .Values.accuknox.certBundlePath | quote }}   
          - name: CERT_BUNDLE_URL
            value: {{ .Values.accuknox.certBundleURL }}
          - name: USE_INSECURE_CONNECTION
            value: {{ .Values.accuknox.useInsecureConnection | quote }}
          - name: DATA_TYPE
            value: "K8TLS"
        volumeMounts:
          - mountPath: /data
            name: datapath
      initContainers:
      - command: ["/bin/sh", "-c"]
        args: ["./k8s_tlsscan"]
        image: "{{ .Values.k8tls.image.repository }}:{{ .Values.k8tls.image.tag }}"
        name: k8tls
        env:
          - name: JSON
            value: "/data/report.json"
        volumeMounts:
        - mountPath: /data
          name: datapath
      restartPolicy: Never
      volumes:
        - name: datapath
          emptyDir: {}

