# Default values for k8tls-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

accuknox:
  authToken: "NO-TOKEN-SET"
  cronTab: "30 9 * * *"
  tenantID: ""
  clusterName: ""
  label: ""
  URL: "cspm.demo.accuknox.com"
  certBundlePath: ""  # Set this for cert local path if needed .
  certBundleURL: ""  # Set this for cert URL if needed (if certBundlePath is set as well certBundlePath will take precedent)
  useInsecureConnection: false  # Set to true if insecure connection is needed
