# Default values for cis-k8s-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


accuknoxJob:
  image:
    repository: accuknox/accuknox-job
    tag: "latest"

kubeBench:
  image:
    repository: docker.io/aquasec/kube-bench
    tag: "v0.9.1"

# To use existing secret updated {imagePullSecrets.name} with your secret name.
imagePullSecrets:
  name: ""
  registry: ""
  username: ""
  password: ""

toolConfig:
  platform: ""
  nodeType: "worker"
  targets: ""
  benchmark: ""
  check: ""
  skip: ""

accuknox:
  authToken: "{{ .Values.global.accuknox.authToken }}"
  URL: "{{ .Values.global.accuknox.url }}"
  tenantID: "{{ .Values.global.accuknox.tenantId }}"
  cronTab: "{{ .Values.global.accuknox.cronTab }}"
  clusterName: "{{ .Values.global.accuknox.clusterName }}"
  label: "{{ .Values.global.accuknox.label }}"
  secretName: "{{ .Values.global.accuknox.secretName }}"
