    on:
      push:
        branches:         
        - '*' 

    name: Accuknox-Job Pipeline

    jobs:
      deploy:
        runs-on: ubuntu-latest

        env:
          ECR_REGION: us-east-1
          ECR_REPO: public.ecr.aws/k9v9d5v2
          CHART_NAME: kube-prometheus-stack

        steps:
          - uses: actions/checkout@v2

          - name: Authenticate ECR public authenticate
            shell: bash
            run: |
              aws ecr-public get-login-password --region  ${{ env.ECR_REGION }} | helm registry login --username AWS --password-stdin  ${{ inputs.ECR_REPO }}
              helm package accuknox-*
              helm push accuknox-* oci://${{ env.ECR_REPO }}