name: Build and Push Job Image to Public ECR

on:
  push:
    paths:
      - "cx-one-job/**"
      - "cx-onprem-sast-job/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to AWS Public ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 \
          | docker login --username AWS --password-stdin public.ecr.aws/k9v9d5v2

      - name: Determine which job changed
        id: detect-folder
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^cx-one-job/'; then
            echo "job=cx-one-job" >> $GITHUB_OUTPUT
          elif git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^cx-onprem-sast-job/'; then
            echo "job=cx-onprem-sast-job" >> $GITHUB_OUTPUT
          else
            echo "No relevant folder changed. Exiting."
            exit 1
          fi

      - name: Build and Push Docker image to Public ECR
        uses: docker/build-push-action@v6
        with:
          context: ./${{ steps.detect-folder.outputs.job }}
          file: ./${{ steps.detect-folder.outputs.job }}/Dockerfile
          push: true
          tags: public.ecr.aws/k9v9d5v2/${{ steps.detect-folder.outputs.job }}:latest
