name: Push SonarQube scans to SaaS

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    - "v[0-9]+.[0-9]+.[0-9]+-*"
    - "v*"

env:
  AK_URL: "https://cspm.accuknox.com"
  AK_SAST_LABEL: "SAST"

jobs:
  scan-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: accuknox/common-gh-actions/actions/sonarqube@main
      with:
        token: ${{ secrets.SQ_TOKEN }}
        qualityGateCheck: 'false'
        args: >
          -Dsonar.projectKey=accuknox-jobs
          -Dsonar.sources=.
        projectKey: accuknox-jobs
        pushToSaas: true
        ak_url: ${{ env.AK_URL }}
        ak_tok: ${{ secrets.AK_PROD_ACCUKNOXTECH_TOKEN }}
        tenant_id: ${{ secrets.AK_PROD_ACCUKNOXTECH_TENANT_ID }}
        label: ${{ env.AK_SAST_LABEL }}